# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: firefly.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'firefly.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfirefly.proto\x12\x07\x66irefly\"\x1d\n\x0cPhaseMessage\x12\r\n\x05phase\x18\x01 \x01(\x01\"\x07\n\x05\x45mpty\"\x1e\n\rPhaseResponse\x12\r\n\x05phase\x18\x01 \x01(\x01\x32z\n\x0e\x46ireflyService\x12\x34\n\x0bUpdatePhase\x12\x15.firefly.PhaseMessage\x1a\x0e.firefly.Empty\x12\x32\n\x08GetPhase\x12\x0e.firefly.Empty\x1a\x16.firefly.PhaseResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'firefly_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PHASEMESSAGE']._serialized_start=26
  _globals['_PHASEMESSAGE']._serialized_end=55
  _globals['_EMPTY']._serialized_start=57
  _globals['_EMPTY']._serialized_end=64
  _globals['_PHASERESPONSE']._serialized_start=66
  _globals['_PHASERESPONSE']._serialized_end=96
  _globals['_FIREFLYSERVICE']._serialized_start=98
  _globals['_FIREFLYSERVICE']._serialized_end=220
# @@protoc_insertion_point(module_scope)
